### ISSUE TITLE
What about using libyui? TUI+GUI in one!

### ISSUE THREAD

**Issue by timofonic** [WarpspeedSCP/derpcalc#1]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by WarpspeedSCP** [comment]
Thank you, this is the first time I've heard of it. I was planning on doing the gui after properly completing the cli. Right now, I have no way to test guis (I don't have a laptop yet, so I'm doing this on my smartphone), so it might not be a good idea right now (guis don't gel with android).

**Comment by WarpspeedSCP** [comment]
I also don't understand many things about project management, and this project is a way for new to learn the ropes.
